Setting up Python Course Outline folder
Pepcoders/Data-Science-Content-English pull request #1
Opened 2022-02-08 10:48 UTC by ritikramuka

2022-02-08 12:15 UTC, aman5898 requested changes
Added Some Comments, Please check

2022-02-08 12:15 UTC, aman5898 commented on Python/README.md
> +    * Basic operations on Lists * 2
Please define

2022-02-08 12:15 UTC, aman5898 commented on Python/README.md
> +    * Basic operations on Tuples * 2
Please define

2022-02-08 12:15 UTC, aman5898 commented on Python/README.md
> +    * Updates in Sets Data Structure in new version of python
Define More function of Sets

2022-02-08 12:15 UTC, aman5898 commented on Python/README.md
> +    * Functions of dictionary
Define More functions of Dictionary

2022-02-08 12:15 UTC, aman5898 commented on Python/README.md
> +* Racap of List, Sets, Tuples and Dictionary
```suggestion
* Recap of List, Sets, Tuples and Dictionary
```

2022-02-08 18:07 UTC, aman5898 requested changes

2022-02-08 18:07 UTC, aman5898 commented on Python/README.md
> +  * Basic operations on Tuples * 2
Name those operations here

2022-02-08 18:07 UTC, aman5898 commented on Python/README.md
> +  * Basics operations on Sets * 2
Name those operations

2022-02-08 18:07 UTC, aman5898 commented on Python/README.md
> +  * Functions of dictionary
Name those functions

2022-02-08 18:22 UTC, aman5898 commented on Python/README.md
> +  * Basic operations on Tuples * 2
```suggestion
  * Basic operations on Tuples * 2
```
Name those operaitons

2022-02-08 18:23 UTC, aman5898 commented on Python/README.md
> +  * Basics operations on Sets * 2
Name operations

2022-02-09 11:07 UTC, ritikramuka commented on Python/README.md
> +    * Basic operations on Lists * 2
done!

2022-02-09 11:07 UTC, ritikramuka commented on Python/README.md
> +    * Basic operations on Tuples * 2
done!

2022-02-09 11:07 UTC, ritikramuka commented on Python/README.md
> +    * Updates in Sets Data Structure in new version of python
done

2022-02-09 11:08 UTC, ritikramuka commented on Python/README.md
> +    * Functions of dictionary
done

2022-02-09 11:08 UTC, ritikramuka commented on Python/README.md
> +  * Functions of dictionary
addressed before!

2022-02-09 11:08 UTC, ritikramuka commented on Python/README.md
> +  * Basic operations on Tuples * 2
addressed before!

2022-02-09 11:09 UTC, ritikramuka commented on Python/README.md
> +  * Basics operations on Sets * 2
Addressed before!

2022-02-16 05:52 UTC, closed without merging